x-pod-volumes: &pod-volumes
  - .:/usr/src/app

x-elasticsearch-volumes: &elasticsearch-volumes
  - ./dockerfile-dev-with-volumes/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

services:
  pod:
    hostname: pod.localhost
    container_name: pod-dev-with-volumes
    hostname: pod.localhost
    build:
      context: .
      dockerfile: dockerfile-dev-with-volumes/pod/Dockerfile
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
      - 8080:8080
    volumes: *pod-volumes

  elasticsearch:
    container_name: elasticsearch-with-volumes
    hostname: elasticsearch.localhost
    build:
      context: .
      dockerfile: dockerfile-dev-with-volumes/elasticsearch/dockerfile-elasticsearch-dev
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes: *elasticsearch-volumes

  redis:
    container_name: redis-with-volumes
    hostname: redis.localhost
    image: ${REDIS_TAG}
    env_file:
      - ./.env.dev
    ports:
      - 6379:6379

  peertube:
    container_name: peertube
    hostname: peertube.localhost
    image: chocobozzz/peertube:develop-bookworm
    ports:
      - 9000:9000
      - 3000:3000
    env_file:
      - peertube.env
    depends_on:
      - postgres
      - redis
      - postfix
    command: sh -c "apt update && apt install --yes neovim ripgrep && yarn install && npm run dev"
    restart: "always"

  postgres:
    image: postgres:13-alpine
    env_file:
      - peertube.env
    restart: "always"

  postfix:
    image: mwader/postfix-relay
    env_file:
      - peertube.env
    restart: "always"

#  redis-commander:
#    container_name: redis-commander
#    hostname: redis-commander.localhost
#    image: rediscommander/redis-commander:latest
#    restart: always
#    environment:
#    - REDIS_HOSTS=local:redis:6379
#    ports:
#    - "8081:8081"
